### ISSUE TITLE
Can this be used with Ruby 1.8.7

### ISSUE THREAD

**Issue by soundarmoorthy** [Shopify/rotoscope#49]
I built this extenison, ruby-debug and debugger-ruby_code_sources with support for 1.8.7. 

I am finally struck at missing debug.h dependencies, which seems to be not present as part of ruby sources 1.8.7 :-(.  

Any help ?

**Comment by jahfer** [comment]
Hi @soundarmoorthy! 

This project [relies very heavily](https://github.com/Shopify/rotoscope/blob/e747e0a7c2cd2e7803ca0358a4555cc2d6e13e33/ext/rotoscope/rotoscope.c#L335) on the [TracePoint API](http://ruby-doc.org/core-2.0.0/TracePoint.html) that was [introduced in Ruby 2.0.0](https://bugs.ruby-lang.org/issues/6895). You may have some better luck with [ruby-prof](https://github.com/ruby-prof/ruby-prof) which doesn't have the same reliance on TracePoint, but its support is still limited to 1.9.3+.

Sorry for the bad news 😢

**Comment by dylanahsmith** [comment]
I'm going to close this since the [gemspec](https://github.com/Shopify/rotoscope/blob/e747e0a7c2cd2e7803ca0358a4555cc2d6e13e33/rotoscope.gemspec#L22) already specifies the require ruby version and we definitely can't rely on ruby versions earlier than 2.0.

Besides, ruby 2.1 and earlier aren't maintained anymore, so won't even get security fixes.
